import json
import os
import re

import frappe

PAGES_TYPES_FILE = "pages.d.ts"

# vue-router path params: `:id`, `:id(\\d+)`, `:id?`, `:path*`, `:path+`
PATH_PARAM_RE = re.compile(r":(\w+)(?:\([^)]*\))?([?*+]?)")
PARAM_VALUE_TYPES = {
	"": "ParamValue",
	"?": "ParamValueZeroOrOne",
	"*": "ParamValueZeroOrMore",
	"+": "ParamValueOneOrMore",
}

TEMPLATE = """// Generated by Studio from this app's pages. Do not edit; it is rewritten on every page export.
import type {{
	ParamValue,
	ParamValueOneOrMore,
	ParamValueZeroOrMore,
	ParamValueZeroOrOne,
	RouteRecordInfo,
	RouteRecordRaw,
	Router,
	RouterOptions,
}} from "vue-router"

interface RouteNamedMap {{
{routes}
}}

declare module "vue-router" {{
	interface TypesConfig {{
		RouteNamedMap: RouteNamedMap
	}}
}}

declare global {{
	type PageName = keyof RouteNamedMap

	// the default export of router.ts
	interface RouterConfig {{
		routerOptions?: Omit<RouterOptions, "history" | "routes"> & {{
			extendRoute?(route: RouteRecordRaw & {{ name: PageName }}): void
		}}
		setup?(router: Router): void | Promise<void>
	}}
}}
"""


def write_pages_types(studio_app: str, app_path: str) -> None:
	"""Write pages.d.ts so router.ts and page scripts get the page titles as typed route names."""
	content = get_pages_types(get_standard_pages(studio_app))
	path = os.path.join(app_path, PAGES_TYPES_FILE)
	if os.path.exists(path) and frappe.read_file(path) == content:
		return
	with open(path, "w") as f:
		f.write(content)


def get_pages_types(pages: list[dict]) -> str:
	routes = "\n".join(f"\t{get_route_info(page)}" for page in pages)
	return TEMPLATE.format(routes=routes)


def get_route_info(page: dict) -> str:
	name = json.dumps(page["page_title"])
	path = json.dumps(page["route"])
	raw_params, params = get_params_types(page["route"])
	return f"{name}: RouteRecordInfo<{name}, {path}, {raw_params}, {params}>"


def get_params_types(route: str) -> tuple[str, str]:
	"""The raw (what router.push takes) and parsed (what route.params holds) params of a route path."""
	params = PATH_PARAM_RE.findall(route)
	if not params:
		return "Record<never, never>", "Record<never, never>"

	def to_type(raw: bool) -> str:
		fields = []
		for name, modifier in params:
			optional = "?" if modifier in ("?", "*") else ""
			fields.append(f"{name}{optional}: {PARAM_VALUE_TYPES[modifier]}<{str(raw).lower()}>")
		return "{ " + "; ".join(fields) + " }"

	return to_type(raw=True), to_type(raw=False)


def get_standard_pages(studio_app: str) -> list[dict]:
	return frappe.get_all(
		"Studio Page",
		filters={"studio_app": studio_app, "is_standard": 1},
		fields=["page_title", "route"],
		order_by="page_title asc",
	)
